.TH cvftest 1 "16 Jun 1998" "dmsdos 0.9.1.3" "dmsdos CVF identification tool"
.SH NAME
cvftest \- dmsdos CVF identification tool
.SH SYNOPSIS

.BI cvftest " filename"

.SH DESCRIPTION
.I cvftest 
tries to find out whether the file (or device)
.I filename
contains a CVF. It does so by reading the first 512 bytes from
.I filename
and checking for certain strings.

.SH RETURN VALUES
.I cvftest 
returns zero (i.e. true) if 
.I filename
has been recognized as a CVF. Otherwise it returns 1. A value >1
indicates an error (e.g. 
.I filename
does not exist or cannot be read).

.SH BUGS
This program is so simple that could be a shell script. But I'm not a shell
hacker, so it's C.

.SH SEE ALSO

Refer to the dmsdos main documentation for further information.
