.TH dmsdosfsck 8 "16 Jun 1998" "dmsdos 0.9.1.3" "dmsdos filesystem checker"
.SH NAME
dmsdosfsck \- dmsdos filesystem checker
.SH SYNOPSIS

.BI dmsdosfsck " [-aflrtvVw] [-d path -d ...] [-u path -u ...] filename"

.SH DESCRIPTION
.I dmsdosfsck
checks the CVF located in
.I filename
for errors and optionally tries to repair errors. It is command-line
compatible with dosfsck(8).

 -a          automatically repair the file system
 -d path (*) drop that file
 -f      (*) salvage unused chains to files
 -l          list path names
 -r          interactively repair the file system
 -t      (*) test for bad clusters
 -u path (*) try to undelete that (non-directory) file
 -v          verbose mode
 -V      (*) perform a verification pass
 -w      (*) write changes to disk immediately
 (*) not yet implemented but option accepted for dosfsck compatibility


.SH BUGS
.I dmsdosfsck
is not yet complete. Be extremely careful with repairs. 

.I It is strongly
.I recommended to let only the native CVF management tools that came with your
.I CVF software package do any repairs.
Use 
.I dmsdosfsck
only to check (which is a read-only operation).

.SH SEE ALSO

Refer to the dmsdos main documentation for further information.
